title: My Learning Azure DevOps
description: A site can show DevOps content
theme: minima

# Navigation links
nav:
  - title: "Home"
    url: /Home
  - title: "Fundamental"
    url: /FundamentalOfLearning
  - title: "Azure Pipeline"
    url: /CI-CD-Azure
  - title: "ARM-Interview"
    url: /ARM-Interview